version: '3.8'

services:
  timezone-api:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  timezone-worker:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - timezone-api